import Link from 'next/link';
import { ReviewStatus } from '@prisma/client';
import { Clock3, Database, Flame, Gauge, Layers, Sparkles, AlertCircle } from 'lucide-react';
import { ReviewActions } from '@/components/review-actions';
import { requireUser } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { requireActiveStudyGuide } from '@/lib/study-guide';
import { getDashboardData } from '@/lib/analytics';
import shell from '@/components/official-shell.module.css';
import styles from './review-screen.module.css';
const dateLabel=(date:Date)=>new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit'}).format(date);
export default async function RevisaoPage({searchParams}:{searchParams?:Promise<{tab?:string;item?:string;view?:string;all?:string}>}) {
 const params=await searchParams; const user=await requireUser(); const guide=await requireActiveStudyGuide(user.id);const now=new Date();
 const [pending,completed,dashboard]=await Promise.all([
 prisma.reviewSchedule.findMany({where:{userId:user.id,studyGuideId:guide.id,status:ReviewStatus.PENDING},include:{subject:{include:{discipline:true,progress:true}}},orderBy:{dueAt:'asc'}}),
 prisma.reviewSchedule.findMany({where:{userId:user.id,studyGuideId:guide.id,status:ReviewStatus.COMPLETED},include:{subject:{include:{discipline:true,progress:true}}},orderBy:{completedAt:'desc'},take:30}),
 getDashboardData(user.id,guide.id)]);
 const nextBySubject=new Map<string,(typeof pending)[number]>(); for(const r of pending) if(!nextBySubject.has(r.subjectId))nextBySubject.set(r.subjectId,r);
 const next=[...nextBySubject.values()];const due=next.filter(r=>r.dueAt<=now);const upcoming=next.filter(r=>r.dueAt>now);const week=upcoming.filter(r=>r.dueAt.getTime()<=now.getTime()+7*86400000);
 const tab=params?.tab==='week'?'week':params?.tab==='completed'?'completed':'today'; const list=tab==='completed'?completed:tab==='week'?week:due;
 const selected=(tab==="completed"?completed:next).find(r=>r.id===params?.item)??list[0];const queue=(tab==='today'?[...due.filter(r=>r.id!==selected?.id),...upcoming]:list.filter(r=>r.id!==selected?.id));
 const progress=selected?.subject.progress; const average=progress?.averagePercentage??0;
 return <div className={`${shell.screen} ${styles.screen}`}>
 <header className={styles.header}><p className={styles.eyebrow}><span>● Sistema de repetição espaçada</span><b>◷ {due.length} pendências para hoje</b></p><h1>Central de Revisões</h1><div><p>Consolide os tópicos com maior taxa de erro ou no intervalo de revisão para fortalecer a memória de longo prazo.</p><nav aria-label="Visualização das revisões"><Link aria-current={params?.view!=='calendar'?'page':undefined} href={`/revisao?tab=${tab}`}>▤ Prioridade</Link><Link aria-current={params?.view==='calendar'?'page':undefined} href={`/revisao?tab=${tab}&view=calendar`}>▥ Calendário</Link></nav></div></header>
 <section className={styles.metrics} aria-label="Indicadores de revisão">{[{label:'Acumulado hoje',value:due.length,detail:'pendentes',icon:AlertCircle,color:'#ba1a1a',pct:next.length?due.length/next.length*100:0},{label:'Aproveitamento médio',value:dashboard.totals.overallPercentage.toFixed(1)+'%',detail:'nos estudos',icon:Gauge,color:'#f59e0b',pct:dashboard.totals.overallPercentage},{label:'Revisões programadas',value:upcoming.length,detail:`de ${next.length} assuntos`,icon:Layers,color:'#4648d4',pct:next.length?upcoming.length/next.length*100:0},{label:'Sequência ativa',value:dashboard.totals.streakDays+' dias',detail:'de estudo',icon:Flame,color:'#10b981',pct:dashboard.totals.streakDays?100:0}].map(m=><article key={m.label}><div><small>{m.label}</small><m.icon size={22} style={{color:m.color}}/></div><p><b>{m.value}</b><span>{m.detail}</span></p><i><em style={{width:m.pct+'%',background:m.color}}/></i></article>)}</section>
 <nav className={styles.tabs} aria-label="Período das revisões"><Link aria-current={tab==='today'?'page':undefined} href="/revisao">Urgentes para hoje <b>{due.length}</b></Link><Link aria-current={tab==='week'?'page':undefined} href="/revisao?tab=week">Esta semana <b>{week.length}</b></Link><Link aria-current={tab==='completed'?'page':undefined} href="/revisao?tab=completed">Concluídas recentemente</Link></nav>
 {params?.view==='calendar'?<section className={styles.calendar}><h2>Calendário de revisões</h2>{(tab==='completed'?completed:next).map(r=><Link key={r.id} href={`/revisao?tab=${r.dueAt<=now?'today':'week'}&item=${r.id}`}><b>{dateLabel(r.dueAt)}</b><span>{r.subject.discipline.name} — {r.subject.name}</span></Link>)}</section>:<div className={styles.columns}><section><div className={styles.sectionHeading}><h2>{tab==='today'?'Revisões de hoje · Prioridade máxima':tab==='week'?'Revisões desta semana':'Concluídas recentemente'}</h2><small>Intervalos de 1 · 7 · 30 dias</small></div>{selected?<article className={styles.hero}><div className={styles.heroTop}><span>{tab==='completed'?'Revisão concluída':selected.dueAt<=now?'● Atenção · revisão pendente':'● Revisão programada'}</span><small><Clock3 size={15}/> {dateLabel(selected.dueAt)} · {selected.intervalDays} dia(s)</small></div><p className={styles.discipline}>{selected.subject.discipline.name}</p><h3>{selected.subject.name}</h3><div className={styles.facts}><span>Acurácia: <b>{average.toFixed(1)}%</b></span><span>Último estudo: {progress?.lastStudiedAt?dateLabel(progress.lastStudiedAt):'ainda não registrado'}</span><span><b>{progress?.wrong??0}</b> erros em {progress?.totalQuestions??0} questões</span></div><div className={styles.retention}><p>Aproveitamento registrado <b>{average.toFixed(1)}%</b></p><i><em style={{width:Math.min(100,average)+'%'}}/></i></div>{tab!=='completed'?<ReviewActions id={selected.id}/>:<p className="mt-8 text-success">Concluída em {selected.completedAt?dateLabel(selected.completedAt):'—'}</p>}<details className={styles.notes}><summary>▤ Anotações do assunto</summary><p>{selected.subject.notes||'Nenhuma anotação cadastrada para este assunto.'}</p><Link href={`/base?tab=assuntos&editSubject=${selected.subjectId}`}>Editar anotações</Link></details></article>:<article className={styles.hero}><h3>{tab==='today'?'Tudo em dia':'Nenhuma revisão neste período'}</h3><p className="mt-4 text-textSecondary">As revisões são atualizadas conforme seus estudos.</p></article>}</section><section><div className={styles.sectionHeading}><h2>Fila programada</h2><Link href={`/revisao?tab=${tab}&all=${params?.all==="1"?"0":"1"}`}>{params?.all==="1"?"Ver menos":"Ver todas"} ({queue.length})</Link></div><div className={styles.queue}>{queue.slice(0,params?.all==="1"?30:4).map(r=><article key={r.id}><span className={styles.queueIcon}><Database size={24}/></span><div><h3 title={r.subject.name}>{r.subject.discipline.name}: {r.subject.name}</h3><p>{dateLabel(r.dueAt)} · Ciclo {r.intervalDays} dias · {(r.subject.progress?.averagePercentage??0).toFixed(0)}% acertos</p></div><Link href={`/revisao?tab=${tab==='completed'?'completed':r.dueAt<=now?'today':'week'}&item=${r.id}`}>Ver revisão</Link></article>)}{!queue.length?<p>Nenhuma outra revisão neste período.</p>:null}</div></section></div>}
 <footer className={styles.tip}><Sparkles size={32}/><div><b>Como funcionam as revisões</b><p>Uma pendência por assunto. Estudar novamente o assunto no ciclo também conclui a revisão vencida. Os próximos intervalos continuam agendados.</p></div><Link href="/planejamento">Ver planejamento</Link></footer>
 </div>;
}

