"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Pause, Play, Square, X } from "lucide-react";
import { toast } from "sonner";

type Active = { id: string; mode: "CYCLE" | "AVULSO"; status: "ACTIVE" | "PAUSED"; version: number; accumulatedSeconds: number; cycle: { position: number; round: number } | null; discipline: { name: string; questionGoal: number }; subject: { name: string; weight: number; averagePercentage: number; lastStudiedAt: string | null } };
type Suggestion = { entry: { orderIndex: number; discipline: { name: string; questionGoal: number } | null }; subject: { name: string; weight: number } | null; roundNumber: number } | null;

function duration(value: number) { return `${String(Math.floor(value / 3600)).padStart(2, "0")}:${String(Math.floor(value / 60) % 60).padStart(2, "0")}:${String(value % 60).padStart(2, "0")}`; }
async function command(body: Record<string, unknown>) { const response = await fetch("/api/active-study-session", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.message ?? "Operação indisponível."); return data; }

export function ActiveStudyPanel({ initialActive, suggestion }: { initialActive: Active | null; suggestion: Suggestion }) {
  const router = useRouter(); const [active, setActive] = useState(initialActive); const [seconds, setSeconds] = useState(initialActive?.accumulatedSeconds ?? 0); const [busy, setBusy] = useState(false); const [questions, setQuestions] = useState(0); const [correct, setCorrect] = useState(0); const [notes, setNotes] = useState("");
  useEffect(() => { setActive(initialActive); setSeconds(initialActive?.accumulatedSeconds ?? 0); }, [initialActive]);
  const activeId = active?.id; const activeStatus = active?.status;
  useEffect(() => { if (!activeId || activeStatus !== "ACTIVE") return; const timer = window.setInterval(() => setSeconds((value) => value + 1), 1000); return () => window.clearInterval(timer); }, [activeId, activeStatus]);
  async function act(body: Record<string, unknown>) { try { setBusy(true); const data = await command(body); if (data.session) { setActive(data.session); setSeconds(data.session.accumulatedSeconds); } else if (data.sessionId) { toast.success(data.idempotent ? "Sessão já havia sido finalizada." : "Sessão concluída; ciclo atualizado."); setActive(null); router.refresh(); } else { setActive(null); toast.success("Sessão cancelada sem alterar o ciclo."); router.refresh(); } } catch (error) { toast.error(error instanceof Error ? error.message : "Erro na sessão."); } finally { setBusy(false); } }
  const current = active ? { discipline: active.discipline.name, subject: active.subject.name, goal: active.discipline.questionGoal, position: active.cycle?.position, round: active.cycle?.round } : suggestion ? { discipline: suggestion.entry.discipline?.name ?? "Sem disciplina", subject: suggestion.subject?.name ?? "Sem assunto", goal: suggestion.entry.discipline?.questionGoal ?? 20, position: suggestion.entry.orderIndex, round: suggestion.roundNumber } : null;
  if (!current) return <section className="rounded-2xl border border-amber-300 bg-amber-50 p-5 text-amber-900 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-200">Configure posições de ciclo com disciplinas e assuntos ativos para iniciar.</section>;
  return <section className="rounded-2xl border border-primary/30 bg-primary/5 p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-primary">{active ? `Sessão ${active.status === "PAUSED" ? "pausada" : "em andamento"}` : "Próxima sessão do ciclo"} · volta {current.round ?? 1}</p><h2 className="mt-1 text-2xl font-black text-slate-900 dark:text-white">{current.discipline} <span className="text-primary">→</span> {current.subject}</h2><p className="mt-1 text-sm text-slate-500">Posição #{current.position ?? "avulsa"} · meta {current.goal} questões · peso {active?.subject.weight ?? suggestion?.subject?.weight ?? 1}</p></div>{active ? <div className="text-3xl font-black tabular-nums text-primary">{duration(seconds)}</div> : null}</div>
    {!active ? <button disabled={busy} onClick={() => act({ command: "start", mode: "CYCLE" })} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-bold text-white disabled:opacity-60"><Play size={16} /> Iniciar sessão</button> : <div className="mt-5 space-y-4"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><label className="text-xs font-bold text-slate-500">Questões<input inputMode="numeric" type="number" min={0} value={questions} onChange={(event) => setQuestions(Math.max(0, Number(event.target.value) || 0))} className="mt-1 h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-base dark:border-slate-700 dark:bg-slate-900" /></label><label className="text-xs font-bold text-slate-500">Acertos<input inputMode="numeric" type="number" min={0} max={questions} value={correct} onChange={(event) => setCorrect(Math.max(0, Number(event.target.value) || 0))} className="mt-1 h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-base dark:border-slate-700 dark:bg-slate-900" /></label><label className="col-span-2 text-xs font-bold text-slate-500">Observação<textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={2} className="mt-1 w-full rounded-lg border border-slate-300 bg-white p-2 text-sm dark:border-slate-700 dark:bg-slate-900" /></label></div><div className="flex flex-wrap gap-2">{active.status === "ACTIVE" ? <button disabled={busy} onClick={() => act({ command: "pause", id: active.id, version: active.version })} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-primary/30 px-4 py-2 font-bold text-primary"><Pause size={16} /> Pausar</button> : <button disabled={busy} onClick={() => act({ command: "resume", id: active.id, version: active.version })} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-primary/30 px-4 py-2 font-bold text-primary"><Play size={16} /> Retomar</button>}<button disabled={busy || correct > questions} onClick={() => act({ command: "finish", id: active.id, version: active.version, questions, correct, minutes: Math.max(1, Math.round(seconds / 60)), notes })} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 py-2 font-bold text-white disabled:opacity-60"><Square size={16} /> Finalizar</button><button disabled={busy} onClick={() => window.confirm("Cancelar sem salvar ou avançar o ciclo?") && act({ command: "cancel", id: active.id, version: active.version })} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-rose-300 px-4 py-2 font-bold text-rose-600"><X size={16} /> Cancelar</button></div></div>}</section>;
}
