import Link from "next/link";
import { requireUser } from "@/lib/auth";
import { requireActiveStudyGuide } from "@/lib/study-guide";
import { getCycleDebug } from "@/lib/cycle-debug";

export default async function CycleDebugPage({ searchParams }: { searchParams?: { simular?: string } }) {
  const user = await requireUser(); const guide = await requireActiveStudyGuide(user.id); const value = Number(searchParams?.simular ?? 0); const total = [20, 100, 200, 500].includes(value) ? value : 0; const debug = await getCycleDebug(user.id, guide.id, total);
  const max = Math.max(1, ...debug.distribution.map((item) => item.count));
  return <div className="space-y-6 pb-10"><header><p className="text-xs font-bold uppercase tracking-widest text-amber-500">Somente leitura</p><h1 className="text-3xl font-black">Painel analítico do ciclo</h1><p className="text-slate-500">Distribuições calculadas pela mesma simulação virtual.</p></header><div className="flex flex-wrap gap-2">{[20,100,200,500].map((amount) => <Link key={amount} href={`/debug/ciclo?simular=${amount}`} className={`rounded-xl px-4 py-2.5 text-sm font-bold ${total === amount ? "bg-primary text-white" : "border border-primary/30 text-primary"}`}>Simular {amount}</Link>)}</div>{total ? <><section className="grid gap-4 md:grid-cols-4"><article className="rounded-2xl bg-primary/10 p-5"><p className="text-xs font-bold uppercase text-primary">Sessões</p><p className="mt-2 text-3xl font-black">{total}</p></article><article className="rounded-2xl border p-5"><p className="text-xs font-bold uppercase text-slate-500">Assuntos</p><p className="mt-2 text-3xl font-black">{debug.distribution.length}</p></article><article className="rounded-2xl border p-5"><p className="text-xs font-bold uppercase text-slate-500">Maior intervalo</p><p className="mt-2 text-3xl font-black">{debug.validator?.maxGap ?? 0}</p></article><article className="rounded-2xl border p-5"><p className="text-xs font-bold uppercase text-slate-500">Validação</p><p className={`mt-2 text-3xl font-black ${debug.validator?.pass ? "text-emerald-600" : "text-rose-600"}`}>{debug.validator?.pass ? "PASS" : "FAIL"}</p></article></section><section className="grid gap-5 xl:grid-cols-2"><article className="rounded-2xl border p-5"><h2 className="font-black">Frequência por assunto</h2><div className="mt-4 space-y-3">{debug.distribution.map((item) => <div key={item.subject}><div className="flex justify-between text-sm"><span>{item.subject}</span><b>{item.count}</b></div><div className="mt-1 h-3 rounded bg-slate-100 dark:bg-slate-800"><div className="h-full rounded bg-primary" style={{width:`${item.count / max * 100}%`}} /></div></div>)}</div></article><article className="rounded-2xl border p-5"><h2 className="font-black">Distribuição percentual</h2><div className="mt-4 grid grid-cols-2 gap-3">{debug.distribution.map((item) => <div key={item.subject} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><p className="truncate text-xs text-slate-500">{item.subject}</p><p className="mt-1 text-xl font-black text-primary">{item.percentage.toFixed(1)}%</p></div>)}</div></article></section><section className="rounded-2xl border p-5"><h2 className="font-black">Sequência simulada</h2><div className="mt-3 max-h-72 overflow-auto text-sm">{debug.simulation.map((row) => <p key={row.session}>#{row.session} · {row.discipline} → {row.subject}</p>)}</div></section></> : null}</div>;
}
