import Link from "next/link";
import { requireUser } from "@/lib/auth";
import { requireActiveStudyGuide } from "@/lib/study-guide";
import { getCycleDebug } from "@/lib/cycle-debug";

export default async function CycleDebugPage({ searchParams }: { searchParams?: { simular?: string } }) {
  const user = await requireUser(); const guide = await requireActiveStudyGuide(user.id); const value = Number(searchParams?.simular ?? 0); const total = [20, 100, 200, 500].includes(value) ? value : 0; const debug = await getCycleDebug(user.id, guide.id, total);
  return <div className="space-y-6 pb-10"><header><p className="text-xs font-bold uppercase tracking-widest text-amber-500">Somente leitura</p><h1 className="text-3xl font-black">Ferramentas avançadas do ciclo</h1><p className="text-slate-500">Simulações usam o motor real sem alterar dados.</p></header><div className="flex flex-wrap gap-2">{[20,100,200,500].map((amount) => <Link key={amount} href={`/debug/ciclo?simular=${amount}`} className={`rounded-xl px-4 py-2.5 text-sm font-bold ${total === amount ? "bg-primary text-white" : "border border-primary/30 text-primary"}`}>Simular {amount}</Link>)}</div>{total ? <section className="rounded-2xl border border-primary/30 p-5"><h2 className="text-xl font-black">Diagnóstico · {total} sessões</h2><p className={`mt-2 font-black ${debug.validator?.pass ? "text-emerald-600" : "text-rose-600"}`}>{debug.validator?.pass ? "PASS" : "FAIL"}</p><p className="text-sm">{debug.validator?.messages.join(" ")}</p><p className="text-sm">Maior intervalo: {debug.validator?.maxGap ?? 0} sessões</p><div className="mt-4 grid gap-1 text-sm">{debug.distribution.map((item) => <p key={item.subject}>{item.subject}: {item.count} ({item.percentage.toFixed(1)}%)</p>)}</div><div className="mt-4 max-h-72 overflow-auto rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-900">{debug.simulation.map((row) => <p key={row.session}>#{row.session} · {row.discipline} → {row.subject}</p>)}</div></section> : null}<section className="space-y-4">{debug.details.map(({ discipline, subjects }) => <article key={discipline.id} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-panelDark"><h2 className="font-black">{discipline.name}</h2>{subjects.map((subject) => <p className="mt-2 text-sm" key={subject.id}>{subject.name} · peso {subject.weight} · score {subject.score} · {subject.nextPriority ? "próxima prioridade" : "fila WRR"}</p>)}</article>)}</section></div>;
}
