import Link from 'next/link';
import { AlertCircle, ArrowRight, Clock3, Database, Flag, Flame, History, Hourglass, Lightbulb, ListChecks, Play, Repeat2, SkipForward } from 'lucide-react';
import { requireUser } from '@/lib/auth';
import { requireActiveStudyGuide } from '@/lib/study-guide';
import { cycleService } from '@/lib/cycle-service';
import { getDashboardData } from '@/lib/analytics';
import { getStudyGuideSettings } from '@/lib/study-guide-settings';
import { prisma } from '@/lib/prisma';
import shell from '@/components/official-shell.module.css';
import styles from './dashboard-screen.module.css';
export default async function DashboardPage(){
 const user=await requireUser();const guide=await requireActiveStudyGuide(user.id);
 const [current,active,preview,dashboard,settings,positions,recent,review]=await Promise.all([
 cycleService.getCurrent(user.id,guide.id),cycleService.getActive(user.id,guide.id),cycleService.preview(user.id,guide.id,2),getDashboardData(user.id,guide.id),getStudyGuideSettings(user.id,guide.id),
 prisma.cycleEntry.count({where:{userId:user.id,studyGuideId:guide.id,active:true}}),
 prisma.studySession.findMany({where:{userId:user.id,studyGuideId:guide.id},orderBy:[{date:'desc'},{createdAt:'desc'}],take:3,include:{subject:{include:{discipline:true}},cycleEntry:{include:{discipline:true,subject:{include:{discipline:true}}}}}}),
 prisma.reviewSchedule.findFirst({where:{userId:user.id,studyGuideId:guide.id,status:'PENDING'},orderBy:{dueAt:'asc'}})]);
 const dateKey=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const today=dashboard.byDay.find(d=>d.date===dateKey);const questions=today?.questions??0;const minutes=today?.estimatedMinutes??0;const goal=dashboard.totals.dailyQuestionsGoal;const pct=goal?questions/goal*100:0;
 const discipline=active?.discipline.name??current?.entry.discipline.name;const subject=active?.subject.name??current?.subject.name;const weight=active?.subject.weight??current?.subject.weight??1;const sessionGoal=active?.discipline.questionGoal??current?.entry.discipline.questionGoal??settings.questionsPerSession;const next=preview[1];
 return <div className={`${shell.screen} ${styles.screen}`}>
 <header className={styles.header}><div className={styles.context}><span>● Ciclo ativo · volta {active?.cycle?.round??current?.roundNumber??1} <i/> Posição #{active?.cycle?.position??current?.entry.orderIndex??'—'} de {positions} · {discipline??'Organize seu ciclo'}</span><Link href="/estatisticas">Seu ritmo de estudos <ArrowRight size={16}/></Link></div><h1>Olá, {user.name?.split(' ')[0]??'Aluno'}.</h1><p>{pct>=100?'Você alcançou a meta de questões de hoje. Continue com o próximo assunto do seu ciclo.':'Seu próximo passo no ciclo está pronto para começar. Continue de onde parou e mantenha sua rotina de estudos.'}</p></header>
 <section className={styles.hero} aria-labelledby="next-study-title"><div className={styles.heroTop}><div><b>{active?'Sessão em andamento':'Próximo estudo'}</b><span>Posição {active?.cycle?.position??current?.entry.orderIndex??'—'} do ciclo · Sugestão pela ordem atual</span></div><Link href="/revisao"><Repeat2 size={18}/> Revisões agendadas</Link></div><h2 id="next-study-title">{discipline??'Organize seu ciclo de estudos'}</h2><p>{subject??'Adicione suas disciplinas e escolha de onde deseja continuar.'}</p><div className={styles.heroMetrics}>{[{icon:Flag,label:'Meta da sessão',value:sessionGoal+' questões'},{icon:Hourglass,label:'Peso no edital',value:'Peso '+weight.toFixed(1)},{icon:AlertCircle,label:'Relevância',value:(active?.subject.averagePercentage??dashboard.subjectStats.find(s=>s.subject===subject&&s.discipline===discipline)?.percentage??0)<70?'Prioridade alta':'Prioridade normal'},{icon:Clock3,label:'Estimativa',value:settings.sessionMinutes+' minutos'}].map(m=><div key={m.label}><span><m.icon size={22}/></span><div><small>{m.label}</small><b>{m.value}</b></div></div>)}</div><div className={styles.actions}>{current||active?<><Link href="/registro?modo=timer" className={styles.primary}><Play size={18}/>{active?'Retomar sessão':'Iniciar agora'}</Link><Link href="/registro"><ListChecks size={18}/>Registrar sem cronômetro</Link></>:<><Link href="/base?import=1" className={styles.primary}>Importar matérias</Link><Link href="/ciclo">Configurar ciclo</Link></>}<Link href="/ciclo" aria-label="Ver ciclo" className={styles.cycleAction}><SkipForward size={20}/></Link></div></section>
 <section className={styles.daily} aria-label="Plano de hoje"><div className={styles.dailyProgress}><div><span>Plano de hoje {pct>=100?<b>Meta batida!</b>:null}</span><strong>{questions} / {goal} questões ({pct.toFixed(0)}%)</strong></div><i role="progressbar" aria-label="Questões de hoje" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.min(100,pct)}><em style={{width:Math.min(100,pct)+'%'}}/></i></div><div><small>Tempo acumulado</small><b><Clock3 size={19}/>{Math.floor(minutes/60)}h {String(minutes%60).padStart(2,'0')}m</b></div><div><small>Sequência</small><b><Flame size={19}/>{dashboard.totals.streakDays} dias</b></div><Link href="/metas">Ajustar metas</Link></section>
 <div className={styles.columns}><section className={styles.recent} aria-labelledby="recent-studies-title"><header><div><small>Registro de sessões</small><h2 id="recent-studies-title">Atividade Recente</h2></div><Link href="/registros">Ver histórico completo <ArrowRight size={17}/></Link></header><div className={styles.recentList}>{recent.map(s=><article key={s.id}><span className={styles.icon}><Database size={24}/></span><div><h3>{s.scope==='GENERAL'?'Revisão geral':s.subject?.discipline.name??s.cycleEntry?.discipline?.name??s.cycleEntry?.subject?.discipline.name??'Disciplina'}</h3><p>{s.scope==='GENERAL'?'Todas as matérias':s.subject?.name??s.cycleEntry?.subject?.name??'Assunto indisponível'}</p><small><History size={14}/>{new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit'}).format(s.date)} · {s.questions} questões resolvidas · {s.estimatedMinutes} min</small></div><div className={styles.score} data-tone={s.percentage>=70?"success":s.percentage>=50?"primary":"warning"}>{s.questions?<><b>{s.percentage.toFixed(0)}%</b><small>{s.correct} acertos</small></>:<><b>{s.estimatedMinutes}m</b><small>Conteúdo</small></>}</div></article>)}{!recent.length?<p>Nenhuma sessão concluída neste guia.</p>:null}</div></section>
 <section className={styles.performance} aria-labelledby="recent-performance-title"><header><div><small>Diagnóstico</small><h2 id="recent-performance-title">Desempenho por Matéria</h2></div><span>Ciclo atual</span></header>{dashboard.disciplineStats.slice(0,3).map(d=><article key={d.discipline}><div><h3>{d.discipline}</h3><b>{d.percentage.toFixed(0)}%</b></div><i><em style={{width:Math.min(100,d.percentage)+'%'}}/></i><p>{d.questions} questões acumuladas · {d.metaLabel}</p></article>)}{!dashboard.disciplineStats.length?<p>O desempenho aparecerá após seus primeiros registros.</p>:null}<footer><Lightbulb size={22}/><p>Seu aproveitamento geral no ciclo é de <b>{dashboard.totals.overallPercentage.toFixed(1)}%</b>.</p></footer></section></div>
 <footer className={styles.next}><SkipForward size={26}/><div><small>A seguir no ciclo:</small> {next?`${next.discipline.name} — ${next.subject.name}`:'Nenhum próximo assunto definido'} {next?<b>#{next.orderIndex}</b>:null}</div>{review?<p><Repeat2 size={17}/> Revisão agendada para {new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit'}).format(review.dueAt)}</p>:null}<Link href="/ciclo">Ver roteiro completo</Link></footer>
 </div>;
}

