import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import * as XLSX from "xlsx";
import { authOptions } from "@/lib/auth";
import { getActiveStudyGuideForUser } from "@/lib/study-guide";
import { getCycleDebug } from "@/lib/cycle-debug";

function sheet(rows: Record<string, unknown>[]) { const value = XLSX.utils.json_to_sheet(rows); value["!autofilter"] = { ref: value["!ref"] ?? "A1" }; value["!cols"] = Array.from({ length: 10 }, () => ({ wch: 22 })); return value; }
export async function GET(request: Request) { const session = await getServerSession(authOptions); if (!session?.user?.id) return NextResponse.json({ message: "Não autenticado" }, { status: 401 }); const guide = await getActiveStudyGuideForUser(session.user.id); if (!guide) return NextResponse.json({ message: "Guia ativo obrigatório" }, { status: 409 }); const total = Math.min(500, Math.max(20, Number(new URL(request.url).searchParams.get("total") ?? 200))); const report = await getCycleDebug(session.user.id, guide.id, total); const book = XLSX.utils.book_new(); const sequence = report.simulation.map((row) => ({ Sessão: row.session, Disciplina: row.discipline, Assunto: row.subject })); const disciplines = [...new Set(report.simulation.map((row) => row.discipline))].map((discipline) => ({ Disciplina: discipline, "Quantidade de sessões": report.simulation.filter((row) => row.discipline === discipline).length, "%": report.simulation.filter((row) => row.discipline === discipline).length / total })); XLSX.utils.book_append_sheet(book, sheet(sequence), "Sequência"); XLSX.utils.book_append_sheet(book, sheet(disciplines), "Disciplinas"); XLSX.utils.book_append_sheet(book, sheet(report.distribution.map((row) => ({ Assunto: row.subject, "Quantidade": row.count, "%": row.percentage / 100 }))), "Assuntos"); XLSX.utils.book_append_sheet(book, sheet([{ Guia: guide.name, "Total de sessões": total, "Todos apareceram": report.allAppeared ? "Sim" : "Não", Status: report.validator?.pass ? "PASS" : "FAIL", "Maior intervalo": report.validator?.maxGap ?? 0 }]), "Resumo"); const data = XLSX.write(book, { type: "buffer", bookType: "xlsx" }); return new NextResponse(data, { headers: { "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Content-Disposition": `attachment; filename="studyflow-ciclo-${total}.xlsx"` } }); }
