import shell from "@/components/official-shell.module.css";
import visual from "@/components/resource-screens.module.css";
import Link from "next/link";
import { CalendarClock, CheckCircle2, Gauge, Lightbulb, Target } from "lucide-react";
import { SyllabusProgressManager } from "@/components/syllabus-progress-manager";
import { requireUser } from "@/lib/auth";
import { getPhaseFiveData } from "@/lib/phase-five-service";
import { resolveSyllabusStatus } from "@/lib/phase-five";
import { requireActiveStudyGuide } from "@/lib/study-guide";

export default async function PlanejamentoPage() {
  const user = await requireUser(); const guide = await requireActiveStudyGuide(user.id); const data = await getPhaseFiveData(user.id, guide.id); const { plan } = data;
  const disciplines = data.disciplines.map((discipline) => ({ id: discipline.id, name: discipline.name, subjects: discipline.subjects.map((subject) => ({ id: subject.id, name: subject.name, weight: subject.weight, status: resolveSyllabusStatus(subject.syllabusProgress?.status, subject.progress?.passages ?? 0) })) }));
  return <div className={`${shell.screen} ${visual.page} ${visual.planning} space-y-5`}>
    <header><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Rota até a prova</p><h1 className="mt-1 text-3xl font-semibold tracking-tight sm:text-4xl">Planejamento e edital</h1><p className="mt-1 text-sm text-textSecondary">Acompanhe a cobertura e entenda por que cada assunto merece atenção.</p></header>
    {plan.examDate ? <section className="rounded-card border border-primary/20 bg-primary/5 p-5 dark:bg-panelDark sm:p-6"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Data da prova</p><h2 className="mt-2 text-3xl font-semibold">{plan.examDate.toLocaleDateString("pt-BR", { timeZone: "UTC" })}</h2><p className="mt-1 text-textSecondary dark:text-textSecondary">{plan.daysRemaining} dias · {plan.weeksRemaining} semanas restantes</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><HeroMetric label="Questões previstas" value={String(plan.questionsUntilExam ?? 0)} /><HeroMetric label="Sessões/semana" value={String(plan.sessionsPerWeek)} /><HeroMetric label="Horas/semana" value={(plan.minutesPerWeek / 60).toFixed(1)} /></div></div></section> : <section className="rounded-card border border-dashed border-primary/40 bg-primary/5 p-6"><h2 className="font-semibold">Defina a data da prova</h2><p className="mt-1 text-sm text-textSecondary">A data permite calcular ritmo semanal, capacidade e risco de cobertura.</p><Link href="/configuracoes" className="mt-4 inline-flex min-h-11 items-center rounded-control bg-primary px-4 text-sm font-semibold text-white">Abrir configurações</Link></section>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><PlanMetric icon={CheckCircle2} label="Cobertura do edital" value={`${plan.coveragePercentage.toFixed(1)}%`} detail={`${plan.coveredSubjects}/${plan.totalSubjects} estudados · ${plan.completedSubjects} concluídos`} /><PlanMetric icon={Target} label="Não iniciados" value={String(plan.remainingSubjects)} detail={`${plan.inProgressSubjects} em andamento`} /><PlanMetric icon={Gauge} label="Ritmo de cobertura" value={plan.subjectsPerWeek === null ? "—" : `${plan.subjectsPerWeek.toFixed(1)}/sem`} detail={plan.onTrack === null ? "Aguardando data" : plan.onTrack ? "Ritmo viável" : "Atenção ao prazo"} /><PlanMetric icon={CalendarClock} label="Carga semanal" value={`${(plan.minutesPerWeek / 60).toFixed(1)}h`} detail={`${plan.sessionsPerWeek} sessões`} /></section>
    <section className="rounded-3xl border border-primary/20 bg-primary/5 p-5 sm:p-6"><div className="flex items-center gap-3"><Lightbulb className="text-primary" /><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Recomendações explicáveis</p><h2 className="text-xl font-semibold">Próximas prioridades</h2></div></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{data.recommendations.map((item, index) => <article key={item.subjectId} className="rounded-2xl bg-surface p-4 dark:bg-panelDark"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-primary">#{index + 1} · {item.discipline}</p><h3 className="mt-1 font-semibold">{item.subject}</h3></div><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">Score {item.score.toFixed(0)}</span></div><p className="mt-3 text-sm leading-6 text-textSecondary dark:text-textSecondary">{item.explanation}</p></article>)}</div></section>
    <SyllabusProgressManager disciplines={disciplines} />
  </div>;
}

function HeroMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-control border border-primary/10 bg-surface p-3 text-center dark:bg-elevated"><p className="text-xl font-semibold">{value}</p><p className="text-[11px] font-semibold text-textSecondary dark:text-textSecondary">{label}</p></div>; }
function PlanMetric({ icon: Icon, label, value, detail }: { icon: typeof Target; label: string; value: string; detail: string }) { return <article className="rounded-2xl border bg-surface p-5 dark:border-white/5 dark:bg-panelDark"><div className="flex items-center justify-between"><p className="text-sm font-semibold text-textSecondary">{label}</p><Icon size={18} className="text-primary" /></div><p className="mt-2 text-3xl font-semibold">{value}</p><p className="mt-1 text-xs text-textSecondary">{detail}</p></article>; }
