import Link from "next/link";
import { CalendarClock, CheckCircle2, Gauge, Lightbulb, Target } from "lucide-react";
import { SyllabusProgressManager } from "@/components/syllabus-progress-manager";
import { requireUser } from "@/lib/auth";
import { getPhaseFiveData } from "@/lib/phase-five-service";
import { requireActiveStudyGuide } from "@/lib/study-guide";

export default async function PlanejamentoPage() {
  const user = await requireUser(); const guide = await requireActiveStudyGuide(user.id); const data = await getPhaseFiveData(user.id, guide.id); const { plan } = data;
  const disciplines = data.disciplines.map((discipline) => ({ id: discipline.id, name: discipline.name, subjects: discipline.subjects.map((subject) => ({ id: subject.id, name: subject.name, weight: subject.weight, status: subject.syllabusProgress?.status ?? "NOT_STARTED" as const })) }));
  return <div className="space-y-7 pb-20">
    <header><p className="text-xs font-black uppercase tracking-[0.16em] text-primary">Rota até a prova</p><h1 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">Planejamento e edital</h1><p className="mt-1 text-sm text-slate-500">Acompanhe a cobertura e entenda por que cada assunto merece atenção.</p></header>
    {plan.examDate ? <section className="rounded-3xl bg-gradient-to-br from-primary to-primarySoft p-6 text-white shadow-soft sm:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-white/75">Data da prova</p><h2 className="mt-2 text-3xl font-black">{plan.examDate.toLocaleDateString("pt-BR", { timeZone: "UTC" })}</h2><p className="mt-1 text-white/80">{plan.daysRemaining} dias · {plan.weeksRemaining} semanas restantes</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><HeroMetric label="Questões previstas" value={String(plan.questionsUntilExam ?? 0)} /><HeroMetric label="Sessões/semana" value={String(plan.sessionsPerWeek)} /><HeroMetric label="Horas/semana" value={(plan.minutesPerWeek / 60).toFixed(1)} /></div></div></section> : <section className="rounded-3xl border border-dashed border-primary/40 bg-primary/5 p-6"><h2 className="font-black">Defina a data da prova</h2><p className="mt-1 text-sm text-slate-500">A data permite calcular ritmo semanal, capacidade e risco de cobertura.</p><Link href="/configuracoes" className="mt-4 inline-flex rounded-xl bg-primary px-4 py-2 text-sm font-black text-white">Abrir configurações</Link></section>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><PlanMetric icon={CheckCircle2} label="Edital concluído" value={`${plan.coveragePercentage.toFixed(1)}%`} detail={`${plan.completedSubjects}/${plan.totalSubjects} assuntos`} /><PlanMetric icon={Target} label="Assuntos restantes" value={String(plan.remainingSubjects)} detail={`${plan.inProgressSubjects} em andamento`} /><PlanMetric icon={Gauge} label="Ritmo necessário" value={plan.subjectsPerWeek === null ? "—" : `${plan.subjectsPerWeek.toFixed(1)}/sem`} detail={plan.onTrack === null ? "Aguardando data" : plan.onTrack ? "Ritmo viável" : "Atenção ao prazo"} /><PlanMetric icon={CalendarClock} label="Carga semanal" value={`${(plan.minutesPerWeek / 60).toFixed(1)}h`} detail={`${plan.sessionsPerWeek} sessões`} /></section>
    <section className="rounded-3xl border border-primary/20 bg-primary/5 p-5 sm:p-6"><div className="flex items-center gap-3"><Lightbulb className="text-primary" /><div><p className="text-xs font-black uppercase tracking-[0.16em] text-primary">Recomendações explicáveis</p><h2 className="text-xl font-black">Próximas prioridades</h2></div></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{data.recommendations.map((item, index) => <article key={item.subjectId} className="rounded-2xl bg-white p-4 dark:bg-panelDark"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase text-primary">#{index + 1} · {item.discipline}</p><h3 className="mt-1 font-black">{item.subject}</h3></div><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-black text-primary">Score {item.score.toFixed(0)}</span></div><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{item.explanation}</p></article>)}</div></section>
    <SyllabusProgressManager disciplines={disciplines} />
  </div>;
}

function HeroMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-white/12 p-3 text-center backdrop-blur"><p className="text-xl font-black">{value}</p><p className="text-[10px] font-bold text-white/75">{label}</p></div>; }
function PlanMetric({ icon: Icon, label, value, detail }: { icon: typeof Target; label: string; value: string; detail: string }) { return <article className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-panelDark"><div className="flex items-center justify-between"><p className="text-sm font-semibold text-slate-500">{label}</p><Icon size={18} className="text-primary" /></div><p className="mt-2 text-3xl font-black">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></article>; }
