"use client";
import { useState } from 'react';
import Link from 'next/link';
import { Database, Pencil, PlusCircle, Search, Trash2, MoreVertical, CheckCircle2, Languages, Network, ChevronLeft, ChevronRight } from 'lucide-react';
import { deleteGuideDisciplineAction, deleteSubjectAction } from '@/app/actions';
import styles from './discipline-catalog.module.css';
type Topic={id:string;name:string;weight:number;notes:string|null;tecReference:string|null;active:boolean;questions:number;percentage:number;studied:boolean};
export function DisciplineCatalog({groups}:{groups:{id:string;name:string;topics:Topic[]}[]}) {
 const [query,setQuery]=useState(''); const [filter,setFilter]=useState('all'); const [page,setPage]=useState(1); const [pageSize,setPageSize]=useState(3);
 const visible=groups.map(g=>({...g,topics:g.topics.filter(t=>(g.name+' '+t.name+' '+(t.notes??'')).toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')) && (filter==='all'||filter==='weight'&&t.weight>=2||filter==='low'&&t.studied&&t.percentage<70))})).filter(g=>g.topics.length||(!query&&filter==='all'));
 const pageCount=Math.max(1,Math.ceil(visible.length/pageSize)); const currentPage=Math.min(page,pageCount); const start=(currentPage-1)*pageSize; const pageGroups=visible.slice(start,start+pageSize);
 return <><div className={styles.filters}><div className={styles.tabs}>{[['all','Todas as Disciplinas'],['weight','Com peso alto (Peso 2+)'],['low','Menor rendimento (<70%)']].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>{setFilter(id);setPage(1)}}>{label}</button>)}</div><div className={styles.search}><label><Search size={16}/><input aria-label="Filtrar tópicos" placeholder="Filtrar tópicos ou termos..." value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label><span>Visualização: detalhada</span></div></div>
 <div className={styles.groups}>{pageGroups.map(g=>{const count=g.topics.length;const questions=g.topics.reduce((n,t)=>n+t.questions,0);const pct=questions?g.topics.reduce((n,t)=>n+t.percentage*t.questions,0)/questions:0;const studied=g.topics.filter(t=>t.studied).length;const language=/portugu|inglês|língua/i.test(g.name);const attention=studied>0&&pct<70;const Icon=language?Languages:/rede/i.test(g.name)?Network:Database;return <article key={g.id} className={styles.card} data-tone={attention?"attention":language?"language":"default"}><header><span className={styles.icon}><Icon size={24}/></span><div className={styles.name}><div className={styles.title}><h2>{g.name}</h2>{attention?<span>Atenção prioritária</span>:null}</div><p><b>Peso {Math.max(1,...g.topics.map(t=>t.weight)).toFixed(1)}</b> · {count} assuntos cadastrados · <span>{pct.toFixed(0)}% acertos geral</span></p></div><div className={styles.progress}><span>Assuntos estudados</span><div><i><em style={{width:`${count?studied/count*100:0}%`}}/></i><b>{count?Math.round(studied/count*100):0}%</b></div></div><Link href={`/base?tab=assuntos&novo=1&discipline=${g.id}`} aria-label={`Adicionar assunto em ${g.name}`}><PlusCircle size={18}/></Link><details><summary aria-label={`Ações de ${g.name}`}><MoreVertical size={18}/></summary><div className={styles.menu}><Link href={`/base?tab=disciplinas&edit=${g.id}`}>Editar disciplina</Link><form action={deleteGuideDisciplineAction}><input type="hidden" name="disciplineId" value={g.id}/><button>Excluir disciplina</button></form></div></details></header><div>{g.topics.map((t,i)=><div className={styles.topic} key={t.id}><span className={styles.number}>{i+1}</span><div className={styles.topicText}><h3>{t.name}</h3><p><b>Peso {t.weight.toFixed(1)}</b><span className={t.studied?styles.studied:''}>{t.studied?<><CheckCircle2 size={13}/> {t.questions} questões resolvidas</>:'Não estudado ainda'}</span>{t.notes?<em>Obs: {t.notes}</em>:t.tecReference?<em>{t.tecReference}</em>:null}</p></div><span className={styles.badge} data-state={!t.active?"paused":!t.studied?"pending":t.percentage<70?"low":"studied"}>{!t.active?'Pausado':!t.studied?'Pendente':t.percentage<70?'Reforço sugerido':'Estudado'}</span><Link href={`/base?tab=assuntos&editSubject=${t.id}`} aria-label={`Editar ${t.name}`}><Pencil size={15}/></Link><form action={deleteSubjectAction}><input type="hidden" name="subjectId" value={t.id}/><button aria-label={`Excluir ${t.name}`}><Trash2 size={15}/></button></form></div>)}{!count?<p className="p-6 text-sm">Nenhum assunto cadastrado.</p>:null}</div></article>})}{!visible.length?<p>Nenhuma disciplina encontrada.</p>:null}</div>
 {visible.length>0?<nav className={styles.pagination} aria-label="Paginação das disciplinas"><p role="status">Disciplinas {start+1}–{Math.min(start+pageSize,visible.length)} de {visible.length}</p><label>Por página <select aria-label="Disciplinas por página" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}>{[3,6,12].map(n=><option key={n} value={n}>{n}</option>)}</select></label><div><button aria-label="Página anterior de disciplinas" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}><ChevronLeft size={16}/></button>{Array.from({length:pageCount},(_,i)=>i+1).filter(n=>n===1||n===pageCount||Math.abs(n-currentPage)<=1).map((n,i,pages)=><span key={n}>{i>0&&n-pages[i-1]>1?<span className={styles.ellipsis}>…</span>:null}<button aria-label={`Página ${n} de disciplinas`} aria-current={n===currentPage?'page':undefined} onClick={()=>setPage(n)}>{n}</button></span>)}<button aria-label="Próxima página de disciplinas" disabled={currentPage===pageCount} onClick={()=>setPage(currentPage+1)}><ChevronRight size={16}/></button></div></nav>:null}
 <footer className={styles.footer}><PlusCircle size={30}/><div><h3>Faltam tópicos do edital?</h3><p>Importe seu edital ou estruture manualmente os assuntos do ciclo.</p></div><Link href="/api/import/base/template">Ver modelo .CSV</Link><Link href="/base?tab=disciplinas&novo=1">Adicionar nova disciplina</Link></footer></>;
}

