"use client";

import { useState } from "react";
import { useFormStatus } from "react-dom";
import { addManualDailyGoal, saveDailyReflection, toggleManualDailyGoal, updateDailyGoalSettings } from "@/app/goals-actions";
import type { DailyGoalsData } from "@/lib/daily-goals-service";

const weekdays = [[1, "Seg"], [2, "Ter"], [3, "Qua"], [4, "Qui"], [5, "Sex"], [6, "Sáb"], [7, "Dom"]] as const;

function Submit({ children }: { children: React.ReactNode }) { const { pending } = useFormStatus(); return <button disabled={pending} className="rounded-xl bg-primary px-4 py-2.5 text-sm font-black text-white disabled:cursor-wait disabled:opacity-60">{pending ? "Salvando…" : children}</button>; }

export function GoalSettingsForm({ data }: { data: DailyGoalsData }) {
  const [dailyMinutes, setDailyMinutes] = useState(data.plan.dailyMinutes);
  const [weeklyQuestions, setWeeklyQuestions] = useState(data.plan.weeklyQuestions);
  const examDate = data.plan.examDate ? data.plan.examDate.toISOString().slice(0, 10) : "";
  const presets = [{ label: "Leve", detail: "Para criar constância", minutes: 45, questions: 100 }, { label: "Equilibrada", detail: "Boa evolução semanal", minutes: 90, questions: 200 }, { label: "Intensa", detail: "Para maior disponibilidade", minutes: 150, questions: 350 }];
  return <form action={updateDailyGoalSettings} className="space-y-6">
    <div><p className="text-sm font-black">Escolha um ponto de partida</p><p className="mt-1 text-sm text-slate-500">Você pode selecionar uma sugestão e ajustar os números abaixo.</p><div className="mt-3 grid gap-3 sm:grid-cols-3">{presets.map((preset) => <button key={preset.label} type="button" onClick={() => { setDailyMinutes(preset.minutes); setWeeklyQuestions(preset.questions); }} className={`rounded-2xl border p-4 text-left transition ${dailyMinutes === preset.minutes && weeklyQuestions === preset.questions ? "border-primary bg-primary/10 ring-2 ring-primary/15" : "border-slate-200 hover:border-primary/40 dark:border-slate-700"}`}><span className="block font-black">{preset.label}</span><span className="mt-1 block text-xs text-slate-500">{preset.detail}</span><span className="mt-3 block text-sm font-bold text-primary">{preset.minutes} min/dia · {preset.questions} questões/semana</span></button>)}</div></div>
    <fieldset><legend className="text-sm font-black">Em quais dias você pretende estudar?</legend><p className="mt-1 text-xs text-slate-500">Dias não selecionados serão tratados como descanso e não quebrarão sua sequência.</p><div className="mt-3 grid grid-cols-4 gap-2 sm:grid-cols-7">{weekdays.map(([value, label]) => <label key={value} className="flex min-h-12 cursor-pointer items-center justify-center rounded-xl border border-slate-200 text-sm font-bold has-[:checked]:border-primary has-[:checked]:bg-primary/10 has-[:checked]:text-primary dark:border-slate-700"><input className="sr-only" type="checkbox" name="activeWeekdays" value={value} defaultChecked={data.settings.activeWeekdays.includes(value)} />{label}</label>)}</div></fieldset>
    <div className="grid gap-4 md:grid-cols-3">
      <label className="rounded-2xl border border-slate-200 p-4 dark:border-slate-700"><span className="text-sm font-black">Tempo por dia</span><span className="mt-1 block text-xs text-slate-500">Vale para qualquer atividade.</span><span className="mt-3 flex items-center gap-2"><input name="dailyMinutes" type="number" min={10} max={720} step={5} value={dailyMinutes} onChange={(event) => setDailyMinutes(Math.max(10, Number(event.target.value) || 10))} className="h-12 min-w-0 flex-1 rounded-xl border border-slate-300 bg-transparent px-3 text-lg font-black dark:border-slate-700" /><b className="text-sm">min</b></span></label>
      <label className="rounded-2xl border border-slate-200 p-4 dark:border-slate-700"><span className="text-sm font-black">Questões por semana</span><span className="mt-1 block text-xs text-slate-500">O sistema distribui entre seus dias.</span><input name="weeklyQuestions" type="number" min={0} max={5000} step={10} value={weeklyQuestions} onChange={(event) => setWeeklyQuestions(Math.max(0, Number(event.target.value) || 0))} className="mt-3 h-12 w-full rounded-xl border border-slate-300 bg-transparent px-3 text-lg font-black dark:border-slate-700" /></label>
      <label className="rounded-2xl border border-slate-200 p-4 dark:border-slate-700"><span className="text-sm font-black">Data da prova</span><span className="mt-1 block text-xs text-slate-500">Opcional; ajuda no planejamento.</span><input name="examDate" type="date" defaultValue={examDate} className="mt-3 h-12 w-full rounded-xl border border-slate-300 bg-transparent px-3 font-bold dark:border-slate-700" /></label>
    </div>
    <div className="rounded-2xl bg-primary/5 p-4 text-sm text-slate-600 dark:text-slate-300"><strong className="text-primary">Como funciona:</strong> o tempo define sua meta diária. As questões são acompanhadas na semana. Videoaulas, lei seca e PDFs somam tempo normalmente.</div>
    <Submit>Salvar minhas metas</Submit>
  </form>;
}

export function ManualGoals({ data }: { data: DailyGoalsData }) { return <div className="space-y-3">{data.manualGoals.map((goal) => <form action={toggleManualDailyGoal} key={goal.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 dark:border-slate-700"><input type="hidden" name="goalId" value={goal.id} /><input type="hidden" name="dayKey" value={data.today.dayKey} /><button aria-label={goal.checkedToday ? `Desmarcar ${goal.title}` : `Concluir ${goal.title}`} className={`grid h-6 w-6 place-items-center rounded-md border ${goal.checkedToday ? "border-emerald-500 bg-emerald-500 text-white" : "border-slate-300"}`}>{goal.checkedToday ? "✓" : ""}</button><span className={goal.checkedToday ? "text-slate-500 line-through" : "font-semibold"}>{goal.title}</span><span className="ml-auto text-[10px] font-black uppercase text-slate-400">{goal.tier === "MINIMUM" ? "Mínimo" : "Meta"}</span></form>)}<form action={addManualDailyGoal} className="flex flex-col gap-2 sm:flex-row"><input required minLength={2} maxLength={100} name="title" placeholder="Meta manual personalizada" className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-transparent px-3 py-2.5 dark:border-slate-700" /><select name="tier" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-panelDark"><option value="MAIN">Meta principal</option><option value="MINIMUM">Mínimo</option></select><Submit>Adicionar</Submit></form></div>; }

export function ReflectionForm({ data }: { data: DailyGoalsData }) { return <form action={saveDailyReflection} className="space-y-4"><input type="hidden" name="dayKey" value={data.today.dayKey} /><fieldset><legend className="text-sm font-black">Como foi o dia?</legend><div className="mt-2 flex flex-wrap gap-2">{[["LEVE", "Leve"], ["BOM", "Bom"], ["DIFICIL", "Difícil"]].map(([value, label]) => <label key={value} className="rounded-xl border border-slate-200 px-4 py-2 text-sm dark:border-slate-700"><input className="mr-2 accent-primary" type="radio" name="mood" value={value} defaultChecked={data.reflection?.mood === value} />{label}</label>)}</div></fieldset><label className="block text-sm font-semibold">O que funcionou?<textarea name="whatWorked" maxLength={500} defaultValue={data.reflection?.whatWorked ?? ""} className="mt-1 min-h-20 w-full rounded-xl border border-slate-200 bg-transparent p-3 dark:border-slate-700" /></label><label className="block text-sm font-semibold">O que ajustar amanhã?<textarea name="adjustTomorrow" maxLength={500} defaultValue={data.reflection?.adjustTomorrow ?? ""} className="mt-1 min-h-20 w-full rounded-xl border border-slate-200 bg-transparent p-3 dark:border-slate-700" /></label><Submit>{data.reflection ? "Atualizar fechamento" : "Encerrar o dia"}</Submit><p className="text-xs text-slate-500">O fechamento não bloqueia novos estudos.</p></form>; }
