"use client";

import { useFormStatus } from "react-dom";
import { addManualDailyGoal, saveDailyReflection, toggleManualDailyGoal, updateDailyGoalSettings } from "@/app/goals-actions";
import { DAILY_GOAL_METRICS, type DailyGoalMetric, type GoalTargets } from "@/lib/daily-goals";
import type { DailyGoalsData } from "@/lib/daily-goals-service";

const labels: Record<DailyGoalMetric, string> = { minutes: "Minutos líquidos", questions: "Questões", sessions: "Sessões", reviews: "Revisões", cyclePosition: "Posições do ciclo", firstStudy: "Primeiro estudo no horário" };
const weekdays = [[1, "Seg"], [2, "Ter"], [3, "Qua"], [4, "Qui"], [5, "Sex"], [6, "Sáb"], [7, "Dom"]] as const;

function Submit({ children }: { children: React.ReactNode }) { const { pending } = useFormStatus(); return <button disabled={pending} className="rounded-xl bg-primary px-4 py-2.5 text-sm font-black text-white disabled:cursor-wait disabled:opacity-60">{pending ? "Salvando…" : children}</button>; }

function TierInputs({ prefix = "", targets }: { prefix?: string; targets: GoalTargets }) {
  return <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="text-xs uppercase tracking-wide text-slate-500"><th className="py-2">Métrica</th><th>Mínimo</th><th>Meta</th><th>Excelente</th></tr></thead><tbody>{DAILY_GOAL_METRICS.filter((metric) => metric !== "firstStudy").map((metric) => <tr key={metric} className="border-t border-slate-100 dark:border-slate-800"><th className="py-2.5 font-semibold">{labels[metric]}</th>{(["minimum", "target", "excellent"] as const).map((tier) => <td key={tier} className="pr-2"><input aria-label={`${labels[metric]} ${tier}`} name={`${prefix}${tier}.${metric}`} type="number" min={0} max={1440} defaultValue={targets[tier][metric]} className="w-full rounded-lg border border-slate-200 bg-transparent px-3 py-2 dark:border-slate-700" /></td>)}</tr>)}</tbody></table></div>;
}

export function GoalSettingsForm({ data }: { data: DailyGoalsData }) {
  return <form action={updateDailyGoalSettings} className="space-y-6">
    <fieldset><legend className="text-sm font-black">Métricas automáticas ativas</legend><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{DAILY_GOAL_METRICS.map((metric) => <label key={metric} className="flex items-center gap-2 rounded-xl border border-slate-200 p-3 text-sm dark:border-slate-700"><input type="checkbox" name="enabledMetrics" value={metric} defaultChecked={data.settings.enabledMetrics.includes(metric)} className="accent-primary" />{labels[metric]}</label>)}</div></fieldset>
    <div><h3 className="font-black">Segunda a sexta</h3><TierInputs targets={data.weekdayTargets} /></div>
    <details className="rounded-2xl border border-slate-200 p-4 dark:border-slate-700"><summary className="cursor-pointer font-black">Metas diferentes no sábado e domingo</summary><div className="mt-5 space-y-6"><div><h4 className="font-bold">Sábado</h4><TierInputs prefix="saturday." targets={data.saturdayTargets} /></div><div><h4 className="font-bold">Domingo</h4><TierInputs prefix="sunday." targets={data.sundayTargets} /></div></div></details>
    <div className="grid gap-5 lg:grid-cols-2"><fieldset><legend className="text-sm font-black">Dias ativos</legend><div className="mt-2 flex flex-wrap gap-2">{weekdays.map(([value, label]) => <label key={value} className="rounded-lg border border-slate-200 px-3 py-2 text-sm dark:border-slate-700"><input className="mr-2 accent-primary" type="checkbox" name="activeWeekdays" value={value} defaultChecked={data.settings.activeWeekdays.includes(value)} />{label}</label>)}</div></fieldset><fieldset><legend className="text-sm font-black">Descanso planejado recorrente</legend><div className="mt-2 flex flex-wrap gap-2">{weekdays.map(([value, label]) => <label key={value} className="rounded-lg border border-slate-200 px-3 py-2 text-sm dark:border-slate-700"><input className="mr-2 accent-primary" type="checkbox" name="plannedRestWeekdays" value={value} defaultChecked={data.settings.plannedRestWeekdays.includes(value)} />{label}</label>)}</div></fieldset></div>
    <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Fuso horário<input name="timeZone" defaultValue={data.settings.timeZone} className="mt-1 block w-full rounded-xl border border-slate-200 bg-transparent px-3 py-2.5 dark:border-slate-700" /></label><label className="text-sm font-semibold">Iniciar primeiro estudo até<input name="firstStudyDeadline" type="time" defaultValue={data.settings.firstStudyDeadline ?? ""} className="mt-1 block w-full rounded-xl border border-slate-200 bg-transparent px-3 py-2.5 dark:border-slate-700" /></label></div>
    <label className="flex items-start gap-3 rounded-xl border border-slate-200 p-4 text-sm dark:border-slate-700"><input type="checkbox" name="includeMockExams" defaultChecked={data.settings.includeMockExams} className="mt-0.5 accent-primary" /><span><strong>Contar simulados nas metas</strong><span className="mt-1 block text-slate-500">Eles continuam aparecendo separadamente no resumo.</span></span></label>
    <Submit>Salvar configuração</Submit>
  </form>;
}

export function ManualGoals({ data }: { data: DailyGoalsData }) { return <div className="space-y-3">{data.manualGoals.map((goal) => <form action={toggleManualDailyGoal} key={goal.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 dark:border-slate-700"><input type="hidden" name="goalId" value={goal.id} /><input type="hidden" name="dayKey" value={data.today.dayKey} /><button aria-label={goal.checkedToday ? `Desmarcar ${goal.title}` : `Concluir ${goal.title}`} className={`grid h-6 w-6 place-items-center rounded-md border ${goal.checkedToday ? "border-emerald-500 bg-emerald-500 text-white" : "border-slate-300"}`}>{goal.checkedToday ? "✓" : ""}</button><span className={goal.checkedToday ? "text-slate-500 line-through" : "font-semibold"}>{goal.title}</span><span className="ml-auto text-[10px] font-black uppercase text-slate-400">{goal.tier === "MINIMUM" ? "Mínimo" : "Meta"}</span></form>)}<form action={addManualDailyGoal} className="flex flex-col gap-2 sm:flex-row"><input required minLength={2} maxLength={100} name="title" placeholder="Meta manual personalizada" className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-transparent px-3 py-2.5 dark:border-slate-700" /><select name="tier" className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 dark:border-slate-700 dark:bg-panelDark"><option value="MAIN">Meta principal</option><option value="MINIMUM">Mínimo</option></select><Submit>Adicionar</Submit></form></div>; }

export function ReflectionForm({ data }: { data: DailyGoalsData }) { return <form action={saveDailyReflection} className="space-y-4"><input type="hidden" name="dayKey" value={data.today.dayKey} /><fieldset><legend className="text-sm font-black">Como foi o dia?</legend><div className="mt-2 flex flex-wrap gap-2">{[["LEVE", "Leve"], ["BOM", "Bom"], ["DIFICIL", "Difícil"]].map(([value, label]) => <label key={value} className="rounded-xl border border-slate-200 px-4 py-2 text-sm dark:border-slate-700"><input className="mr-2 accent-primary" type="radio" name="mood" value={value} defaultChecked={data.reflection?.mood === value} />{label}</label>)}</div></fieldset><label className="block text-sm font-semibold">O que funcionou?<textarea name="whatWorked" maxLength={500} defaultValue={data.reflection?.whatWorked ?? ""} className="mt-1 min-h-20 w-full rounded-xl border border-slate-200 bg-transparent p-3 dark:border-slate-700" /></label><label className="block text-sm font-semibold">O que ajustar amanhã?<textarea name="adjustTomorrow" maxLength={500} defaultValue={data.reflection?.adjustTomorrow ?? ""} className="mt-1 min-h-20 w-full rounded-xl border border-slate-200 bg-transparent p-3 dark:border-slate-700" /></label><Submit>{data.reflection ? "Atualizar fechamento" : "Encerrar o dia"}</Submit><p className="text-xs text-slate-500">O fechamento não bloqueia novos estudos.</p></form>; }
